/** @type {import('tailwindcss').Config} */
let designTheme = { colors: {}, spacing: {} }
try {
  // Generated by scripts/sync-figma-tokens.js
  // Provides { colors, spacing } mapped to CSS variables
  designTheme = require('./tokens/tailwind-theme.cjs')
} catch (e) {
  // Run `npm run figma:sync` to generate tokens theme
}
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}', // For future App Router migration
  ],
  corePlugins: {
    // Disable Tailwind's container to avoid conflicts with Bootstrap
    container: false,
  },
  theme: {
    extend: {
      // Design Token System - CSS Custom Properties from Figma
      colors: {
        // Generated tokens
        ...designTheme.colors,
        // Legacy aliases for backward compatibility (remove after full migration)
        'black': 'var(--onio-color-primary)',
        'grey': 'var(--onio-color-muted)', 
        'yellow': 'var(--onio-color-secondary)',
        'orange': 'var(--onio-color-accent)',
        'light-grey': 'var(--onio-color-background)',
        'danger': 'var(--onio-color-alert)',
      },
      spacing: {
        // Generated tokens
        ...designTheme.spacing,
        // Legacy custom spacing (keep for backward compatibility)
        '18': '4.5rem',
        '72': '18rem',
        '84': '21rem',
        '96': '24rem',
      },
      fontFamily: {
        'onio': ['Inter', 'system-ui', 'sans-serif'],
        'onio-display': ['Inter', 'Georgia', 'serif'],
      },
      fontSize: {
        // Design system typography scale - MATCHES ORIGINAL CSS EXACTLY
        // Note: Base font is 62.5% so 1rem = 10px
        // Standard typography scale
        'xs': ['var(--onio-font-size-body-xs)', { lineHeight: '1.4' }],        // 12px - Extra small body
        'sm': ['var(--onio-font-size-body-sm)', { lineHeight: '1.4' }],        // 14px - Small body text  
        'base': ['var(--onio-font-size-body)', { lineHeight: '1.625' }],       // 16px→20px responsive (default body)
        'lg': ['var(--onio-font-size-h6)', { lineHeight: '1.185185' }],        // 27px→23.625px responsive (h6) FIXED
        'xl': ['var(--onio-font-size-h5)', { lineHeight: '1.142857' }],        // 35px→26px→24px responsive (h5) FIXED  
        '2xl': ['var(--onio-font-size-h4)', { lineHeight: '1.166667' }],       // 48px all breakpoints (h4) FIXED  
        '3xl': ['var(--onio-font-size-h3)', { lineHeight: '1.3' }],            // 28px (h3)
        '4xl': ['var(--onio-font-size-h2)', { lineHeight: '1.25' }],           // 32px (h2)
        '5xl': ['var(--onio-font-size-h1)', { lineHeight: '1.3' }],            // 40px (h1)
        '6xl': ['var(--onio-font-size-hero)', { lineHeight: '1' }],            // 60px (hero text)
        
        // Body text variants (desc-- classes from legacy CSS)
        'body-xl': ['var(--onio-font-size-body-xl)', { lineHeight: '1.142857' }],   // 35px→26px→24px responsive (desc--large exact match)
        'body-lg': ['var(--onio-font-size-body-lg)', { lineHeight: '1.5' }],   // 18px (mobile body text size)
        'body': ['var(--onio-font-size-body)', { lineHeight: '1.625' }],       // 16px→20px responsive  
        'body-sm': ['var(--onio-font-size-body-sm)', { lineHeight: '1.4' }],   // 14px (desc--small)
        'body-xs': ['var(--onio-font-size-body-xs)', { lineHeight: '1.4' }],   // 12px (captions)
      },
      boxShadow: {
        'onio-light': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'onio-medium': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'onio-heavy': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
  // Safelist classes that might be used dynamically
  safelist: [
    // Color classes
    'bg-primary', 'bg-secondary', 'bg-accent', 'bg-muted', 'bg-background', 'bg-white', 'bg-alert',
    'text-primary', 'text-secondary', 'text-accent', 'text-muted', 'text-white',
    'border-primary', 'border-secondary', 'border-accent', 'border-muted', 'border-white', 'border-alert',
    
    // Hover states
    'hover:bg-primary', 'hover:bg-secondary', 'hover:bg-accent', 'hover:bg-white', 'hover:bg-alert',
    'hover:text-primary', 'hover:text-secondary', 'hover:text-accent', 'hover:text-white',
    'hover:border-primary', 'hover:border-secondary', 'hover:border-accent', 'hover:border-white',
    
    // Button specific classes
    'hover:!bg-primary', 'hover:!text-white', 'bg-primary/10',
    
    // Typography classes (headings and body text)
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl', 'text-6xl',
    'text-body-xl', 'text-body-lg', 'text-body', 'text-body-sm', 'text-body-xs',
    
    // Spacing classes (padding, margin, gap)
    'p-xs', 'p-sm', 'p-md', 'p-lg', 'p-xl', 'p-2xl',
    'm-xs', 'm-sm', 'm-md', 'm-lg', 'm-xl', 'm-2xl',
    'gap-xs', 'gap-sm', 'gap-md', 'gap-lg', 'gap-xl', 'gap-2xl',
    'px-xs', 'px-sm', 'px-md', 'px-lg', 'px-xl', 'px-2xl',
    'py-xs', 'py-sm', 'py-md', 'py-lg', 'py-xl', 'py-2xl',
    'mx-xs', 'mx-sm', 'mx-md', 'mx-lg', 'mx-xl', 'mx-2xl',
    'my-xs', 'my-sm', 'my-md', 'my-lg', 'my-xl', 'my-2xl',
  ]
}
