export const customSelectStyles = {
  option: (provided, state) => ({
    ...provided,
    borderBottom: "1px dotted pink",
    color: "var(--onio-color-primary)",
    fontWeight: 500,
    fontSize: "1.8rem",
    lineHeight: "2.2rem",
    padding: 10,
    paddingLeft: 12,
    paddingRight: 12,
    border: "none",
    backgroundColor: state.isSelected ? "var(--onio-color-background)" : "transparent",
    transition: "background-color 0.4s ease",
    "&:hover": {
      backgroundColor: "var(--onio-color-background)",
      cursor: "pointer",
    },
  }),
  control: (provided) => ({
    ...provided,
    backgroundColor: "transparent",
    color: "var(--onio-color-white)",
    borderRadius: 0,
    border: "none",
    borderBottom: "0.2rem solid",
    borderBottomColor: "var(--onio-color-white)",
    boxShadow: "none",
    "&:hover": {
      borderColor: "var(--onio-color-white)",
    },
  }),
  singleValue: (provided) => ({ ...provided, color: "var(--onio-color-white)" }),
  valueContainer: (provided) => ({
    ...provided,
    margin: 0,
    padding: "0 3px",
    border: "none",
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "var(--onio-color-white)",
  }),
  input: (provided) => ({
    ...provided,
    margin: 0,
    padding: 0,
    height: "4.8rem",
  }),
  menu: (provided) => ({
    ...provided,
    borderRadius: 0,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: "0.3rem",
  }),
  indicatorSeparator: () => ({ display: "none" }),
};
