// AUTO-GENERATED by scripts/sync-figma-api.js
// Maps Tailwind theme to CSS custom properties from Figma REST API
// Last updated: 2025-09-04T13:16:22.574Z

module.exports = {
  "colors": {
    "primary": "var(--onio-color-primary)",
    "secondary": "var(--onio-color-secondary)",
    "accent": "var(--onio-color-accent)",
    "muted": "var(--onio-color-muted)",
    "background": "var(--onio-color-background)",
    "white": "var(--onio-color-white)",
    "alert": "var(--onio-color-alert)"
  },
  "spacing": {
    "xs": "var(--onio-spacing-xs)",
    "sm": "var(--onio-spacing-sm)",
    "md": "var(--onio-spacing-md)",
    "lg": "var(--onio-spacing-lg)",
    "xl": "var(--onio-spacing-xl)",
    "2xl": "var(--onio-spacing-2xl)"
  },
  "fontSize": {
    "hero": "var(--onio-font-size-hero)",
    "h1": "var(--onio-font-size-h1)",
    "h2": "var(--onio-font-size-h2)",
    "h3": "var(--onio-font-size-h3)",
    "h4": "var(--onio-font-size-h4)",
    "h5": "var(--onio-font-size-h5)",
    "h6": "var(--onio-font-size-h6)",
    "body": "var(--onio-font-size-body)",
    "body-lg": "var(--onio-font-size-body-lg)",
    "body-sm": "var(--onio-font-size-body-sm)"
  }
}
