// AUTO-GENERATED by scripts/sync-figma-tokens.js
// Maps Tailwind theme to CSS custom properties from Figma
module.exports = {
  "colors": {
    "primary": "var(--onio-color-primary)",
    "secondary": "var(--onio-color-secondary)",
    "accent": "var(--onio-color-accent)",
    "muted": "var(--onio-color-muted)",
    "background": "var(--onio-color-background)",
    "white": "var(--onio-color-white)",
    "alert": "var(--onio-color-alert)"
  },
  "spacing": {
    "xs": "var(--onio-spacing-xs)",
    "sm": "var(--onio-spacing-sm)",
    "md": "var(--onio-spacing-md)",
    "lg": "var(--onio-spacing-lg)",
    "xl": "var(--onio-spacing-xl)",
    "2xl": "var(--onio-spacing-2xl)"
  }
}
