
export default {
    global: 'global',
    header: 'header',
    footer: 'footer',
    home: 'homepage',
    about: 'about-us',
    investors: 'investor',
    privacyPolicy: 'privacy-policy',
    privacySetting: 'privacy-settings',
    app: 'app',
    career: 'career',
    careerLanding: 'career-landing',
    productLanding: 'product-landing',
    technologyRedefined:  'technology-redefined',
    batterylessRemote: 'batteryless-remote',
    onioZero:  'onio-zero',
    news: 'news',
    newsLanding: 'news-landing',
    newsCount: 'news-count',
    blog: 'blog',
    blogList: 'blog-list',
    blogCount: 'blog-count',
    blogCategories: 'blog-categories',
    blogLanding: 'blog-landing',
    blogDetail: 'blog-detail',
    writer: 'writer',
    smartHub: 'smart-hub',
    shelfLabel: 'shelf-label',
    energyEmulator: 'energy-emulator',

}